{{- if .Values.secret_env }}
{{- if eq .Values.secret_env.enable true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.deployment.name }}-secret
  namespace: {{ $.Values.namespace }}
type: Opaque
data:
  {{- range $secret_key, $secret_value := $.Values.secret_env.value }}
  {{ $secret_key }}: {{ $secret_value | b64enc | quote }}
  {{- end }}
---
{{- end }}
{{- end }}